### ISSUE TITLE
Custom CA with type: kubernetes.io/tls secret

### ISSUE THREAD

**Issue by DavidMachacek** [scholzj/strimzi-custom-ca-test#2]
When I want to use my own CA with external TLS authentication, i required to create my own secrets:
i.e.
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    strimzi.io/ca-key-generation: "0"
  name: b01-cluster-ca
  labels:
    strimzi.io/cluster: b01
    strimzi.io/kind: Kafka
type: Opaque
data:
  ca.key: xxx
```

This is completly fine until I want this key to be used by cert-manager that requires tls-type of secrets. So I tried to change the secret type from Opaque to kubernetes.io/tls and duplicated the ca.key and tls.key to conain the same value.
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    purpose: "source TLS for cluster issuer"
  name: b01-cluster-tls
  labels:
    strimzi.io/cluster: b01
    strimzi.io/kind: Kafka
type: kubernetes.io/tls
data:
  tls.key: xxx
  ca.key: xxx
  tls.crt: yyy
```

But when I do that, the strimzi cluster does not start anymore with NullPointerException:

$ oc describe kafka b01
```
Name:         b01
Namespace:    infra-kafka
Labels:       app.kubernetes.io/instance=infra-kafka
Annotations:  argocd.argoproj.io/tracking-id: infra-kafka:kafka.strimzi.io/Kafka:infra-kafka/b01
API Version:  kafka.strimzi.io/v1beta2
Kind:         Kafka
Metadata:
  Creation Timestamp:  2024-12-17T10:02:07Z
  Generation:          1
  Resource Version:    8802109
  UID:                 d5a2b500-bb85-4a33-8227-6623d3b87a24
Spec:
  Clients Ca:
    Generate Certificate Authority:  false
  Cluster Ca:
    Generate Certificate Authority:  false
...
Status:
  Conditions:
    Last Transition Time:  2024-12-17T10:02:07.506847840Z
    Message:               Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
    Reason:                NullPointerException
    Status:                True
    Type:                  NotReady
  Observed Generation:     1
Events:                    <none>
```

It seems Strimzi accepts only Opaque secrets, but I would prefer to use tls types instead. Workaround is to create multiple secrets (one opaque and one type: kubernetes.io/tls), but this just doesnt feel right. I would prefer to have just one. Is this desired behavior? Can I create pull-secret to fix this? Or what is the decision behind this behavior?
